### PR TITLE
Add Contact Page

### PR DESCRIPTION
**Pull request by ShreeluSantosh**
## Description

* Created a new directory `Contact` in `/src/pages` directory
* Add `index.js` and `style.css` in `Contact`
* Updated `App.js` with new line to set up Route for ContactUs

```
<Route exact={true} path="/ContactUs" element={<Contact />} />
```
* Updated `/src/components/header/nav/nav.js` to include ContactUs router in Contact Button in Nav bar

```
<li className='list-inline-item'>
    <Button onClick={props.closeNav}><Link to={'/ContactUs'}>Contact</Link></Button>
</li>
```

## Motivation and Context

The Contact button in navbar does not lead to a Contact Us page. Instead, it redirects us to the current page. On examining the repo code, there is no code for setting up Contact Us page

Resolves Issue #83 

## How Has This Been Tested?

I tested the changes in a separate test directory to avoid any undesirable changes to the forked and cloned repository

**Testing enviroment**
* Brave browser [Version 1.66.118 Chromium: 125.0.6422.147 (Official Build) (64-bit)]
* Visual Studio Code [Version 1.90.0]

## Screenshots (if appropriate):

https://github.com/MAVRICK-1/Nest-Ondc/assets/94289402/c17c7022-b02a-40ba-94d1-1268e038374e

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ShreeluSantosh** [comment]
Linked Issue: #83

**Comment by Sahilll15** [comment]
@ShreeluSantosh keep this in a flex manner contact form should be in the right and rest other on the left and the contact form should be the focus

**Comment by ShreeluSantosh** [comment]
Okay, will modify accordingly and make a new PR

**Comment by Sahilll15** [comment]
It was not necessary to close this pr u could have just made a new commot
and pushed it

**Comment by ShreeluSantosh** [comment]
Updated, Please check @Sahilll15

**Comment by Sahilll15** [comment]
@ShreeluSantosh please just share a screen shot of it

**Comment by ShreeluSantosh** [comment]
@Sahilll15 
Updated Contact page

**Comment by Sahilll15** [comment]
> @Sahilll15 
> 
> Updated Contact page
> 
> 

Lgtm

**Pull request merged**
