### PR TITLE
new feature

### PR DESCRIPTION
**Pull request by MetiUmashri**
The placeholder has an enhancement as suggested in the issue #7

### CODE REVIEW

**Comment by MetiUmashri** [comment]
@akbatra567 please look into it

**Comment by akbatra567** [comment]
> @akbatra567 please look into it

I still can see the lock files. Could you remove them?

**Comment by MetiUmashri** [comment]
is the yarn.lock file creating the mess?

**Comment by akbatra567** [comment]
> is the yarn.lock file creating the mess?
@MetiUmashri 

It's not about mess. 
The main idea is that you only commit the changes that are intended and related to the task you are doing.
And avoid anything unrelated, until it had a merge conflict or a dependency. 

Why we do it ?
- Easier for reviewers to review your code. 
- Your changes are cleaner and focused.
- You avoid any random unintentional merge conflicts for others or yourself. 

Now, Imagine you've a package-lock.json file where you have like 20 merge conflicts and the file is quite large that would be pain to resolve.

**Pull request closed without merging**
