### PR TITLE
changed style in navbar

### LINKED ISSUE #84: Adding a colour when we hover in navbar on groceries to make it more attractive  @ssoc
when we hover on item it should be highlighted with  website's default colour (light green)

Screenshot (110)

@MAVRICK-1 please assign me this

### PR DESCRIPTION
**Pull request by Krishna100604**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Krishna100604** [comment]
@MAVRICK-1 please accept my pull request

**Comment by MAVRICK-1** [comment]
@Krishna100604 mark the issue on description

**Comment by Krishna100604** [comment]
> @Krishna100604 mark the issue on description

check issue no #84 ,it is the pull request for the same

**Comment by MAVRICK-1** [comment]
@Krishna100604 great work can you remove the hover effect from navbar field only , not the dropdown list

**Pull request closed without merging**
