### PR TITLE
jump to top button added

### PR DESCRIPTION
**Pull request by harinisayani**
I have added jump to top up button in footer section. To move to the home page by clicking the arrow button.

## Screenshots (if appropriate):

https://github.com/MAVRICK-1/Nest-Ondc/assets/143276011/347c593f-ac31-4cdb-a464-2728b1f75bf1

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by MAVRICK-1** [comment]
@harinisayani make it visible while scrolling

**Comment by Sahilll15** [comment]
@harinisayani please make a better button or use other available buttons

**Comment by harinisayani** [comment]
Ok, I will do it.

**Comment by Sahilll15** [comment]
@harinisayani  it has conflicts in package-json which can cause issue in application performance and can break as well ill just pull the updated code and then add the following changes as it is a small change

**Review by akbatra567 — APPROVED** [review]
Looks good to me

**Comment by akbatra567** [comment]
@harinisayani, approved the PR. but you'd need to resolve the changes so it can be merged.

**Comment by harinisayani** [comment]
Hi @akbatra567,
I have resolved conflicts.
Please merge it.

**Pull request merged**
