### PR TITLE
open graph implementation and added site description #45

### LINKED ISSUE #45: Open Graph implementation for the website
### **Feature Request: Add Open Graph Support**

**Feature missing.**

Currently, links from this website don't display rich previews on social media, making shared content look unattractive.

**Describe the solution you'd like**

Add Open Graph tags to our website, including:

- `og:title`
- `og:description`
- `og:image`
- `og:url`

This will ensure our links generate engaging previews on social media.

**Alternatives considered**

Considered using Twitter Card tags, but Open Graph tags are more universally supported across various platforms.

Adding these tags will improve the appearance of our shared content.

### PR DESCRIPTION
**Pull request by Trident09**
## Title: Open Graph Implementation and Site Description Update

- Implemented Open Graph tags in the static side of the website.
- Added a site description for concise summarization of content.
- Removed unnecessary template material to improve code structure.

## Motivation and Context: 
- Enhances social media sharing and visibility on platforms like Facebook and Twitter.
- Improves search engine results with a clear site description.
- Streamlines code and enhances website performance.

## Testing: 
- Verified presence of Open Graph tags and updated site description through browser's developer tools.
- Tested social media sharing to ensure correct information display.

## Screenshots (if appropriate):

OG Image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

Fix : https://github.com/MAVRICK-1/Nest-Ondc/issues/45#issue-2332370876

### CODE REVIEW

**Review by Trident09 — COMMENTED** [review]
Please check the pr

**Review by kushagra-singhh — APPROVED** [review]
LGTM !!

**Comment by MAVRICK-1** [comment]
@Trident09 great work , can change the link to this https://nest-ondc-arzx.vercel.app/

**Comment by Trident09** [comment]
yeah I'll do that Thank you.

**Review by Trident09 — COMMENTED** [review]
I have updated the link.

**Review by kushagra-singhh — APPROVED** [review]

**Pull request merged**
